"""empty message

Revision ID: 0d6ef13f68a8
Revises: 6d9de252c978
Create Date: 2023-02-22 15:37:25.711992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6ef13f68a8'
down_revision = '6d9de252c978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index('fk_cart_product_id_product')
        batch_op.create_foreign_key(batch_op.f('fk_cart_product_id_product'), 'product', ['product_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index('fk_order_payment_id_payment')
        batch_op.create_foreign_key(batch_op.f('fk_order_payment_id_payment'), 'payment', ['payment_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index('fk_order_items_order_id_order')
        batch_op.drop_index('fk_order_items_product_id_product')
        batch_op.create_foreign_key(batch_op.f('fk_order_items_order_id_order'), 'order', ['order_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_order_items_product_id_product'), 'product', ['product_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('fk_product_product_category_id_product_category')
        batch_op.drop_index('fk_product_shop_id_shop')
        batch_op.create_foreign_key(batch_op.f('fk_product_product_category_id_product_category'), 'product_category', ['product_category_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_product_shop_id_shop'), 'shop', ['shop_id'], ['id'])

    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_index('fk_product_image_product_id_product')
        batch_op.create_foreign_key(batch_op.f('fk_product_image_product_id_product'), 'product', ['product_id'], ['id'])

    with op.batch_alter_table('product_property', schema=None) as batch_op:
        batch_op.drop_index('fk_product_property_product_id_product')
        batch_op.create_foreign_key(batch_op.f('fk_product_property_product_id_product'), 'product', ['product_id'], ['id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index('fk_sales_order_id_order')
        batch_op.drop_index('fk_sales_shop_id_shop')
        batch_op.create_foreign_key(batch_op.f('fk_sales_order_id_order'), 'order', ['order_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_shop_id_shop'), 'shop', ['shop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_shop_id_shop'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_order_id_order'), type_='foreignkey')
        batch_op.create_index('fk_sales_shop_id_shop', ['shop_id'], unique=False)
        batch_op.create_index('fk_sales_order_id_order', ['order_id'], unique=False)

    with op.batch_alter_table('product_property', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_property_product_id_product'), type_='foreignkey')
        batch_op.create_index('fk_product_property_product_id_product', ['product_id'], unique=False)

    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_image_product_id_product'), type_='foreignkey')
        batch_op.create_index('fk_product_image_product_id_product', ['product_id'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_shop_id_shop'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_product_product_category_id_product_category'), type_='foreignkey')
        batch_op.create_index('fk_product_shop_id_shop', ['shop_id'], unique=False)
        batch_op.create_index('fk_product_product_category_id_product_category', ['product_category_id'], unique=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_items_product_id_product'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_order_items_order_id_order'), type_='foreignkey')
        batch_op.create_index('fk_order_items_product_id_product', ['product_id'], unique=False)
        batch_op.create_index('fk_order_items_order_id_order', ['order_id'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_payment_id_payment'), type_='foreignkey')
        batch_op.create_index('fk_order_payment_id_payment', ['payment_id'], unique=False)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cart_product_id_product'), type_='foreignkey')
        batch_op.create_index('fk_cart_product_id_product', ['product_id'], unique=False)

    # ### end Alembic commands ###
