"""empty message

Revision ID: 2a4ca3a5555e
Revises: 
Create Date: 2023-02-16 09:21:20.315042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a4ca3a5555e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_address_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_cart_product_id_product'), 'product', ['product_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_cart_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_order_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_order_payment_id_payment'), 'payment', ['payment_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_order_items_order_id_order'), 'order', ['order_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_order_items_product_id_product'), 'product', ['product_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=800),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_product_shop_id_shop'), 'shop', ['shop_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_product_product_category_id_product_category'), 'product_category', ['product_category_id'], ['id'])

    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('public_dir',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_product_image_product_id_product'), 'product', ['product_id'], ['id'])

    with op.batch_alter_table('product_property', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('value',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_product_property_product_id_product'), 'product', ['product_id'], ['id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_sales_order_id_order'), 'order', ['order_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_shop_id_shop'), 'shop', ['shop_id'], ['id'])

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=3000),
               nullable=False)
        batch_op.alter_column('slogan',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('payment_account',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('logo_dir',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_shop_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.String(length=255), nullable=False))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('picture_dir',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.alter_column('picture_dir',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('roles')

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shop_user_id_user'), type_='foreignkey')
        batch_op.alter_column('logo_dir',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('payment_account',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('slogan',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=3000),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_shop_id_shop'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_order_id_order'), type_='foreignkey')

    with op.batch_alter_table('product_property', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_property_product_id_product'), type_='foreignkey')
        batch_op.alter_column('value',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_image_product_id_product'), type_='foreignkey')
        batch_op.alter_column('public_dir',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_product_category_id_product_category'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_product_shop_id_shop'), type_='foreignkey')
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=800),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_items_product_id_product'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_order_items_order_id_order'), type_='foreignkey')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_payment_id_payment'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_order_user_id_user'), type_='foreignkey')
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cart_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cart_product_id_product'), type_='foreignkey')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_address_user_id_user'), type_='foreignkey')

    # ### end Alembic commands ###
