"""empty message

Revision ID: 5ce3e42f4f3f
Revises: a95844ee1dff
Create Date: 2023-03-07 16:26:57.471611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ce3e42f4f3f'
down_revision = 'a95844ee1dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
