"""empty message

Revision ID: 602cf6e4e3ec
Revises: 6c9a4fc762df
Create Date: 2023-02-05 09:57:27.017879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602cf6e4e3ec'
down_revision = '6c9a4fc762df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
