"""empty message

Revision ID: 6c9a4fc762df
Revises: 73eb58dca0fe
Create Date: 2023-02-04 11:25:52.249322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c9a4fc762df'
down_revision = '73eb58dca0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=4, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.DECIMAL(precision=4, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)

    # ### end Alembic commands ###
